### PR TITLE
Support for advanced recurrence rules, attendees, reminders and fixes

### LINKED ISSUE #99: Flutter build api --release issue
I have been gotten issue with retrieveCalendars when build release.

If I build project by code, device_calendar work well. But if I build release apk and then install by generated apk. this method cannot retrieveCalendars on device.

Please help me about this.

Thanks

### PR DESCRIPTION
**Pull request by MaikuB**
- Related to #109 
- Fixes #99.
- Event title has also been made optional to address #72 
- Made list of events and calendars read-only to address #113 
- Adds support for retrieving who the organiser is #73. This includes returning the email address of attendees
- Adds support for modifying attendees of an event #75 
- Adds support for creating reminders relative to start time of an event #105

### CODE REVIEW

**Comment by nickrandolph** [comment]
This PR also fixes https://github.com/builttoroam/flutter_plugins/issues/114

File: device_calendar/lib/src/device_calendar.dart [hunk 1]
```diff
@@ -61,14 +60,14 @@ class DeviceCalendarPlugin {
   ///
   /// Returns a [Result] containing a list of device [Calendar]
   Future<Result<List<Calendar>>> retrieveCalendars() async {
```
Comment (nickrandolph) [inline device_calendar/lib/src/device_calendar.dart]: Should this return UnmodifiableListView instead of List - https://api.dartlang.org/stable/2.4.1/dart-collection/UnmodifiableListView-class.html

File: device_calendar/android/src/main/kotlin/com/builttoroam/devicecalendar/DeviceCalendarPlugin.kt [hunk 2]
```diff
@@ -53,7 +62,7 @@ class DeviceCalendarPlugin() : MethodCallHandler {
 
     companion object {
         @JvmStatic
-        fun registerWith(registrar: Registrar): Unit {
+        fun registerWith(registrar: Registrar) {
             val context: Context = registrar.context()
             val activity: Activity? = registrar.activity()
```
Comment (nickrandolph) [inline device_calendar/android/src/main/kotlin/com/builttoroam/devicecalendar/DeviceCalendarPlugin.kt]: Is there a reason for the creation of two MethodChannel

File: device_calendar/android/src/main/kotlin/com/builttoroam/devicecalendar/CalendarDelegate.kt [hunk 3]
```diff
@@ -86,30 +92,28 @@ class CalendarDelegate : PluginRegistry.RequestPermissionsResultListener {
...
-        }
+        val cachedValues: CalendarMethodsParametersCacheModel = _cachedParametersMap[requestCode]
+                ?: // unlikely scenario where another plugin is potentially using the same request code but it's not one we are tracking so return to
+                // indicate we're not handling the request
+                return false
 
         when (cachedValues.calendarDelegateMethodCode) {
-            RETRIEVE_CALENDARS_METHOD_CODE -> {
+            RETRIEVE_CALENDARS_REQUEST_CODE -> {
                 return handleRetrieveCalendarsRequest(permissionGranted, cachedValues, requestCode)
```
Comment (nickrandolph) [inline device_calendar/android/src/main/kotlin/com/builttoroam/devicecalendar/CalendarDelegate.kt]: All these handle methods seem to do a check on permissionGranted - can we pull out this check and do it before the when clause?

Comment (MaikuB) [reply device_calendar/android/src/main/kotlin/com/builttoroam/devicecalendar/CalendarDelegate.kt]: refactored this out now. thanks

File: device_calendar/android/src/main/kotlin/com/builttoroam/devicecalendar/DeviceCalendarPlugin.kt (hunk 2 above)
Comment (MaikuB) [reply device_calendar/android/src/main/kotlin/com/builttoroam/devicecalendar/DeviceCalendarPlugin.kt]: there should've only been one. removed now

File: device_calendar/lib/src/device_calendar.dart (hunk 1 above)
Comment (MaikuB) [reply device_calendar/lib/src/device_calendar.dart]: ah yep, thanks
